### PR TITLE
Use `xdg-open` for open on Linux (Zeal >= 0.2)

### LINKED ISSUE #30: Zeal Support
Zeal now supports `dash-plugin://` scheme, and registers itself as a protocol handler on Windows and Linux.  The old `--query` argument has been deprecated, and will be removed in `0.3.0` release.

I'll [add](https://github.com/zealdocs/zeal/issues/448) support for `&prevent_activation=true` as well. I had no idea about this parameter. Zeal simply ignores unknown parameters, so starting to pass `&prevent_activation=true` immediately would not cause a problem.

I have just updated Zeal's [website](https://zealdocs.org/usage.html) with a link to this nice plugin.

### PR DESCRIPTION
**Pull request by blakeembrey**
Closes #30

### CODE REVIEW

**Comment by dirtyvader** [comment]
Hello.

I've tried to use your patch, but xdg-open complains about missing hostname in the scheme.

Here is the error:
"Malformed URL
Invalid hostname (contains invalid characters); source was 'xdg-open "dash-plugin://query=.SetFlags" '
scheme = "dash-plugin", host = ""
"

**Comment by blakeembrey** [comment]
Thanks for trying it. That seems like a deal breaker. @trollixx, how did you expect this to work? Am I using something wrong.

**Comment by trollixx** [comment]
Sorry for the delay — long vacation. I've just run 'xdg-open
"dash-plugin://query=.SetFlags" ' from the terminal without any issues.
I'll check with Atom when I get home.

**Comment by blakeembrey** [comment]
Awesome, thank you. Hope you enjoyed your vacation :smile:

**Comment by dirtyvader** [comment]
In fact actually, the problem is not due to xdg-open itself. When xdg-open is execute in a desktop environment, like KDE or Gnome, it delegate the opening to this desktop environment. In the case of KDE, it's  kioclient, which accept to open the dash-plugin URI scheme only if you have added a new mime type (like application/zeal or so), register a new protocol handler and call kioclient like this :

kioclient execute dash-plugin://query=.SetFlags application/zeal

pretty annoying

**Comment by trollixx** [comment]
@dirtyvader you should have no need for doing anything manually as long as `zeal.desktop` file is properly installed.

**Comment by trollixx** [comment]
I've just tested this PR with Atom 1.4.0 and it works perfectly.

**Comment by blakeembrey** [comment]
@trollixx Thank you! I'll look at adding an error handler in case @dirtyvader's case pops up though.

**Comment by trollixx** [comment]
Great! Let me know should any issues arise.

**Comment by blakeembrey** [comment]
Done :+1: https://github.com/blakeembrey/atom-dash/releases/tag/v1.6.0

**Comment by dirtyvader** [comment]
@trollixx Yeah it should... I use the zeal-git package on Archlinux, it contain the .desktop file but no protocol handler registered after installation.

**Pull request merged**
